spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: AccountService
          uri: lb://AccountService
          predicates:
            - Path=/accounts/**
        - id: TransactionService
          uri: lb://TransactionService
          predicates:
            - Path=/transactions/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    hostname: localhost

server:
  port: 8080

logging:
  level:
    com.bankingsystem: DEBUG
