server:
  port: 8082

spring:
  application:
    name: TransactionService
  datasource:
    url: jdbc:mysql://mysql:3306/accountdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: userpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

account:
  service:
    url: http://api-gateway:8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/